---
# First, find out what distro our hosts are running
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution }}

- hosts:
  - Debian
  tasks:
    # Debian doesn't install python-apt and python-pycurl by default;
    # install it so we can use apt and apt_key later
    - name: install Ansible requirements
      shell: "apt-get -y install {{ item }}"
      with_items:
        - python-apt
        - python-pycurl
    # Debian doesn't install the lsb-release package by default;
    # install it so we can use ansible_lsb.codename later
    - name: Install lsb-release package
      apt: >
        name="lsb-release"
        state=present

- hosts:
  - "Ubuntu:&deploy"
  - "Debian:&deploy"
  tasks:
    - name: "install apt-cacher-ng package"
      apt: >-
        name="{{ item }}"
        state=present
      with_items:
        - apt-cacher-ng
    - name: "enable apt-cacher-ng service"
      service: >-
        name="{{ item }}"
        state=started
      with_items:
        - apt-cacher-ng

- hosts:
  - Ubuntu
  - Debian
  tasks:
    - name: configure apt to use proxy
      lineinfile: >
        dest="/etc/apt/apt.conf.d/50proxy"
        line='Acquire::http::Proxy "http://192.168.122.1:3142/";'
        state=present
        create=yes
    - name: add ceph.com package signing key
      apt_key: >
        url="http://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc"
        id="17ED316D"
        state=present
    - name: add ceph.com package repository
      apt_repository: >
        repo="deb http://ceph.com/debian-{{ ceph_release }}/ {{ ansible_lsb.codename }} main"
        state=present
    - name: update package cache
      apt: >
        update_cache=yes
    - name: install packages
      apt: >
        name="{{ item }}"
        state=present
      with_items:
        - ntp
        - ceph
        - ceph-deploy
    - name: enable services
      service: >-
        name="{{ item }}"
        state=started
      with_items:
        - ntp

- hosts:
  - "CentOS:&deploy"
  - "Red Hat Enterprise Linux:&deploy"
  tasks:
    - name: "install yum cache packages"
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - yum-plugin-local
        

- hosts:
  - CentOS
  - Red Hat Enterprise Linux
  tasks:
    - name: disable unnecessary yum plugins
      ini_file: >
        dest="/etc/yum/pluginconf.d/{{ item }}.conf"
        section="main"
        option="enabled"
        value="0"
      with_items:
        - fastestmirror
    - name: install NFS utilities
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - nfs-utils
        - portmap
        - libselinux-python

- hosts:
  - "CentOS:&deploy"
  - "Red Hat Enterprise Linux:&deploy"
  tasks:
    - name: create yum cache directory
      file: >
        path={{ item }}
        state=directory
      with_items:
        - "/var/lib/yum/plugins/local"
    - name: share yum cache via NFS
      lineinfile: >
        dest=/etc/exports
        line="{{ item }} 0.0.0.0/0.0.0.0(rw,no_root_squash)"
      with_items:
        - "/var/lib/yum/plugins/local"
      notify: "reload NFS"
    - name: enable NFS server
      service: >-
        name=nfs
        state=started
  handlers:
    - name: "reload NFS"
      service: >        
        name=nfs
        state=restarted

- hosts:
  - "CentOS:!deploy"
  - "Red Hat Enterprise Linux:!deploy"
  tasks:
    - name: mount local yum cache
      mount: >
        name={{ item }}
        src="alice:{{ item }}"
        fstype=nfs
        opts=rw
        state=mounted
      with_items:
        - "/var/lib/yum/plugins/local"

- hosts:
  - "CentOS"
  - "Red Hat Enterprise Linux"
  tasks:
    - name: "install yum cache packages"
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - yum-plugin-local

- hosts:
  - "CentOS"
  - "Red Hat Enterprise Linux"
  tasks:
    - name: install redhat-lsb-core package
      yum: >
        name="redhat-lsb-core"
        state=present


- hosts:
  - CentOS
  - Red Hat Enterprise Linux
  tasks:
    - name: add package signing keys
      rpm_key: >
        key="{{ item }}"
        state=present
      with_items:
        - 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'
        - 'https://fedoraproject.org/static/0608B895.txt'
        - 'https://fedoraproject.org/static/352C64E5.txt'
    - name: add package repositories
      shell: >
        yum-config-manager --add-repo http://{{ item }}
      with_items:
        - "download.fedoraproject.org/pub/epel/{{ ansible_lsb.major_release }}/{{ ansible_architecture }}"
        - "ceph.com/rpm-{{ ceph_release }}/rhel{{ ansible_lsb.major_release }}/{{ ansible_architecture }}"
        - "ceph.com/rpm-{{ ceph_release }}/rhel{{ ansible_lsb.major_release }}/noarch"
    - name: exclude Ceph packages from EPEL
      ini_file: >
        dest="/etc/yum.repos.d/download.fedoraproject.org_pub_epel_{{ ansible_lsb.major_release }}_{{ ansible_architecture }}.repo"
        section="download.fedoraproject.org_pub_epel_{{ ansible_lsb.major_release }}_{{ ansible_architecture }}"
        option="exclude"
        value="ceph*"
    - name: install packages
      yum: >
        name="{{ item }}"
        state=present
      with_items:
        - ntp
        - ceph
        - ceph-deploy
    - name: enable services
      service: >-
        name="{{ item }}"
        state=started
      with_items:
        - ntpd
